### ISSUE TITLE
Synology not able to connect to Chromecast/SqueezeLite devices

### ISSUE THREAD

**Issue by joshuacarroll19** [crieke/RoonServer_Synology_Installer#1]
Hi,

I've been trying to setup a new RoonServer Core running on the a Synology NAS (ds1618 running DSM 6.2-23739 Update 2). So far I'm able to connect to the core server via Roon client, but Chromecast/SqueezeLite devices are either not showing up (SqueezeLite) or, showing up (Chromecasts), but pressing enable does nothing. As a test I tried moving Roon core to a windows server on the same network, and I was able to pickup the SqueezeLite devices, and play audio through them without issue. 
 - I was thinking it was a firewall issue on the Synology NAS, but its currently turned off.
 - I uninstalled any other Audio software running on the Synology NAS to eliminate conflicts.

Any help would be appreciated. 
Joshua

**Comment by crieke** [comment]
Try switching off Synology's vSwitch feature (if enabled). It currently does not play well with RoonServer.

**Comment by joshuacarroll19** [comment]
Woot, that did the trick. Fortunately I was only testing out the VM functionally of the NAS. Thanks!
